### ISSUE TITLE
Empty executions

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#11]
Do you have any ideas why several executions are empty? Even configuration data is empty, how come? 
My database is full of those empty entries, even after cleaning all Executions in the database, one day later its full of empty entries such like that (please see image below):

![image](https://user-images.githubusercontent.com/473074/163411838-e6769717-a5d0-40c2-8f02-9c0f973a5c4e.png)

**Comment by airguru** [comment]
I have reworked the creation of executions, this should not happen again. Relevant commit: 7a9d3ddab71fbb0e8094b3f0f6d71b8403d7e8c5

@PedroRossa98 can you please test this on pendulum js?
