### ISSUE TITLE
Sidebar not showing on tablet or mobile

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#12]
Unfortunately this code is not working, at least for me:

```javascript
$("#showmobiletabletsidebar").click(function(){
    $('.mobiletabletsidebar.animate .menu').transition({
        animation : 'swing right',
        duration  : 1000
      })
    ;
    $('#mobiletabletsidebar').removeClass('hidden');
});
``` 

So clicking the icon below does nothing and you can't navigate the site on mobile!

![image](https://user-images.githubusercontent.com/473074/163452846-e68b3566-e3b0-4cc4-afd8-22531c522cbe.png)

**Comment by PedroRossa98** [comment]
I will look into to this, thanks for the feedback

**Comment by bgeneto** [comment]
> I will look into to this, thanks for the feedback

Is this bug confirmed already? For me the whole web interface does not work properly on mobile (phone or tablet). DataTables seems not to be responsive...

**Comment by airguru** [comment]
Can you please test it using the code from the dev (`cleanup`) branch?  https://github.com/e-lab-FREE/FREE_Web/tree/cleanup
I have tested it only using dev tools and I am seeing the sidebar (however the page usability is poor imho).

**Comment by bgeneto** [comment]
> Can you please test it using the code from the dev (`cleanup`) branch? https://github.com/e-lab-FREE/FREE_Web/tree/cleanup I have tested it only using dev tools and I am seeing the sidebar (however the page usability is poor imho).

Sure I will... but I think it is safer to also put those sidebar links in the main screen/page, something like this (sorry for the "Navigation" misspell):

![proposta-pg](https://user-images.githubusercontent.com/473074/165389850-ab738b86-d482-4804-9cce-8ac1105d3aa5.png)

**Comment by bgeneto** [comment]
@airguru did you noticed the avatar picture I'm using? Could you please exchange your default +3MB image with this one (link below)? TIA. 

[eu.png](https://github.com/bgeneto/wpa-django/blob/master/free-server/free/static/free/images/eu.png)

**Comment by PedroRossa98** [comment]
We are using this one now https://github.com/e-lab-FREE/FREE_Web/blob/cleanup/free/static/free/images/eu.png

**Comment by airguru** [comment]
> but I think it is safer to also put those sidebar links in the main screen/page, something like this (sorry for the "Navigation" misspell):

I think the content of the main screen will eventually display something even more interesting than navigation (I would guess something like a dashboard or so), so I would leave that as a separate issue. We need to make sure the sidebar 100% works as that's the only thing present in all pages.

**Comment by bgeneto** [comment]
Ok, the sidebar now works (almost) properly in the `cleanup` branch. But it can only be expanded, not contracted :-( and that's bad practice IMHO. 

![image](https://user-images.githubusercontent.com/473074/165808868-4532eb44-633f-4b4b-b667-d2fcd7105c78.png)
