### ISSUE TITLE
e-lab logo not showing

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#18]
The e-lab logo on login page is not showing for me, please serve this file (`elab_logo.png`) locally in the static folder in order to avoid the reverse proxy or any other web server to block the remote http (unsecure) request to this file (if you have cross-origin request disabled for security reasons, for example). 

![Untitled](https://user-images.githubusercontent.com/473074/165558953-632c930f-45fc-4f21-933b-380c96871a46.png)

**Comment by airguru** [comment]
Fixed in d83a7566e8e667b371bffa62e97e9bd871335163.
