### ISSUE TITLE
Last_online Update

### ISSUE THREAD

**Issue by PedroRossa98** [e-lab-FREE/FREE_Web#19]
Hi,
it seems that we are only updating this parameter when we change the experience of en queue to R, and updates it on the endpoint /result. This is what concludes with my tests.

![image](https://user-images.githubusercontent.com/64550870/165645853-1e16e122-a91b-482c-8b7f-3f127e828417.png)

![image](https://user-images.githubusercontent.com/64550870/165646139-878badd9-d59a-4653-8877-b16101371b7c.png)

**Comment by airguru** [comment]
Hopefully fixed by [8d23c20](https://github.com/e-lab-FREE/FREE_Web/pull/13/commits/8d23c2086607101d69d679252775ea2d2d9f30ba)

**Comment by PedroRossa98** [comment]
From @joao-n-silva :

"hello Pavel Kuriščák, i found the problem.

on class next execution, the query that you perfomer only returned anythinf if there was an execution queued. (status = ´Q').

the test that you perfomed had an execution queue.

if there is no execution on the quque, the query returns None and the verifications is never executed, and the state of the apparatus is never saved.>

https://github.com/e-lab-FREE/FREE_Web/blob/80a9817ff349bff2197d474f21d46dd605f823f0/free/views/api.py#L196-L211

here is a code that solves it:

the printas are the comments:

```python3
class NextExecution(generics.RetrieveAPIView):
    """
    Returns the earliest started execution.
    This is supposed to be the next execution that the apparatus should perform.
    **APPARATUS AUTHENTICATION REQUIRED**
    """
    permission_classes = [ApparatusOnlyAccess]
    serializer_class = ExecutionSerializer
    def get_object(self):
        print('entering next execution')
        obj = Apparatus.objects.filter(id=self.kwargs['id']).first()
        print(obj)
        if obj == None:
            print('The aparatus does not exist')
            return obj
        else:
            print('the apparatus exist - verifying permitions')
            x = self.check_object_permissions(self.request, obj)
            obj.save()
            print('the apparatus exist and is authorized')
            obj = Execution.objects.filter(status='Q', apparatus_id=self.kwargs['id']).order_by('start').first()
            if obj:
                print('there is an execution')
                obj.save()
        return obj
```

**Comment by PedroRossa98** [comment]
Fix:

https://github.com/e-lab-FREE/FREE_Web/blob/fbf3f9cfd49896e253f3ec078e01a44522246a95/free/views/api.py#L197-L214
