### ISSUE TITLE
No video

### ISSUE THREAD

**Issue by airguru** [e-lab-FREE/FREE_Web#20]
It follows some screenshots from the web interface in the cleanup branch. 
Some moveable elements (e.g.: `<div class="draggable">`) are floating around several pages...  Maybe the lines below are the offending ones: 

```
<!-- necessary for movable window -->
<script>
   var selectedStream = ; // syntax error here !!!
   server = "";
</script>
```

I had no video at all. Could not start any experiment. No xhr janus requests  at all. 

![Screenshot 2022-04-27 154016](https://user-images.githubusercontent.com/473074/165597521-3764da39-b6f9-43b6-9f85-0f1d28037773.jpg)

![Screenshot 2022-04-27 154031](https://user-images.githubusercontent.com/473074/165597567-4f269a68-a94f-4e5e-a0f0-be58cb9f5e6e.jpg)

_Originally posted by @bgeneto in https://github.com/e-lab-FREE/FREE_Web/issues/17#issuecomment-1111358891_

**Comment by airguru** [comment]
I propose that we troubleshoot this in some kind of video call session.

**Comment by bgeneto** [comment]
> I propose that we troubleshoot this in some kind of video call session.

No problem. I'm available today, tomorrow also (with time restrictions). Does @PedroRossa98 got it working in his environment?

**Comment by bgeneto** [comment]
This issue is already solved with all the previous accepted commits... I think we can close it now.
