### ISSUE TITLE
MonteCarlo submodule not pulling

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#21]
Hi! 

The MonteCarlo submodule is not pulling/cloning. You can test it by cloning to an empty directory. I think you should use

```
git submodule add https://github.com/e-lab-FREE/FREE_MonteCarlo.git dev_MonteCarlo
```

in order to add the submodule to the `.gitmodules` file and then commit the changes.

**Comment by PedroRossa98** [comment]
I think the submodule is there (as you can see it here 93714cc6cead08ae55db83788a837becdcffde23) you need to run the following comands:

```
git submodule init
```

```
git submodule update --init 
```

This should pull the files.

**Comment by PedroRossa98** [comment]
Tell me if this works for you @bgeneto and sorry for the delay on the reply

**Comment by airguru** [comment]
@bgeneto @PedroRossa98 i think we can close this issue, right?

**Comment by bgeneto** [comment]
Yeah! Closed.
