### ISSUE TITLE
App crashes when creating user

### ISSUE THREAD

**Issue by airguru** [e-lab-FREE/FREE_Web#37]
@bgeneto

**Comment by bgeneto** [comment]
Unfortunately it is still not working... but I found a way that works..  just put a wrong confirmation password and submit... :-) 

![error-500](https://user-images.githubusercontent.com/473074/169312047-9c0f7613-23e1-4e6b-b345-3111c926bae3.gif)

**Comment by bgeneto** [comment]
I've just tried with the template database file and it worked. I will add all the users, pendulums etc.. manually :-( to this template file and see if it works... maybe my database is somehow in a bad state.

**Comment by bgeneto** [comment]
Ok. Just migrated our server to mariadb DBMS and all the user creation process seems to be working even while there are several pendulums running and users connected.

**Comment by airguru** [comment]
I really think we are confusing two issues together. Notice that now you don't see user category selector until after the second step of user creation.

**Comment by bgeneto** [comment]
I think you get it right. Two  different issues here. This branch/PR is OK. I just noticed later that, although showing the same error 500, the issue now is sporadic and is related to the database file been locked, as reported previously.
