### ISSUE TITLE
login form not showing error message

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#39]
Currently if a user enters wrong credentials the error message is not showing. 
We need to add the `error` class to the login `form` tag at `free/templates/free/login.html` so it reads: 

```
<form class="ui large form error" method="POST"  ...
```

**Comment by airguru** [comment]
If you already know what to do, could you write a fix for that? :) This seems like a good candidate to also merge to master for 0.5.1
