### ISSUE TITLE
CSRF Failed: CSRF token from the 'X-Csrftoken' HTTP header has incorrect length

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#8]
Getting this error sometimes. Don't know why but sometimes after clicking "Save" the "Submit" button keeps disabled. The request and response follows: 

**URL**: http://IP:8000/api/v1/execution/181
**Payload**: {"id":181,"apparatus":1,"protocol":1,"config":{"deltaX":10,"samples":15}}
**Status code**: 403 Forbidden 
**Cookie**: csrftoken=s5r7lRtyEpgpx26uSDoMPW9zpl5SoqlObhOxInME529018aVGLLRRvRUa87yvrBn; sessionid=v2gipdz39qqnc5vv78znb842yecobzb7; django_language=pt
X-**CSRFToken**: s5r7lRtyEpgpx26uSDoMPW9zpl5SoqlObhOxInME529018aVGLLRRvRUa87yvrBn; django_language=pt
**Response**: {"detail":"CSRF Failed: CSRF token from the 'X-Csrftoken' HTTP header has incorrect length."}

Seems just right for me. Don't know why CSRF is failing... Any ideias?

**Comment by airguru** [comment]
Problem identified in function `getCookie` in `plotly_results.js`. @PedroRossa98  is on track to solving that.

**Comment by airguru** [comment]
Relevant commit [c58e73c](https://github.com/e-lab-FREE/FREE_Web/pull/13/commits/c58e73c8beae68ff247f86b663b5f5b2a1fa2ede)
