### ISSUE TITLE
Support usage behind reverse proxy 

### ISSUE THREAD

**Issue by bgeneto** [e-lab-FREE/FREE_Web#9]
Please add lines below to Django app `settings.py` in order to allow the web interface to accessed behind a nginx or caddy reverse proxy:

```python
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
```

Also change the file `pendulum/templates/free/experiments/pendulum.html` to refer to the correct Janus host:

```javascript
var selectedStream =  document.getElementById('video-config').textContent;
var server = null;
if (window.location.protocol === 'http:')
    server = "http://" + window.location.hostname + ":8088/janus";
else
    server = "https://" + window.location.hostname + ":8089/janus";
```

**Comment by airguru** [comment]
Sounds like a good idea! @PedroRossa98: are you ok with 2nd part? Will it break something on your side?

**Comment by PedroRossa98** [comment]
About the secound part, in the future version we will have this option on the `freeweb/settings.py` (I think this solves the http vs https problem)

```
JANUS_SERVER_ADDRESSS="http://localhost:8088/janus"
JANUS_API_SECRET='janusrocks'
JANUS_STREAM_ADMIN_KEY = "supersecret"
```

**Comment by airguru** [comment]
Partially adressed with [bd7a058](https://github.com/e-lab-FREE/FREE_Web/pull/13/commits/bd7a058086eb0ad2576fdd632941e5495948954e)

**Comment by airguru** [comment]
@PedroRossa98 Regarding the second part, I propose changing `experiment.html` to include:
```
{% block headscript %}
<script id="janus_url" type="application/json">{{janus_url}}</script>
...
```

Of course, first we must get it into the context data. Will you be able to do that or should I prepare it for you?

**Comment by bgeneto** [comment]
> 

Please correct me if I am wrong: I think janus api secret is not used anywhere in the code... so it is not necessary! If you think otherwise please indicate where this secret is been used.

**Comment by PedroRossa98** [comment]
On the janus server you can put a admin key witch you will need to give to the FREE server so it can create and list the video streams.

**Comment by bgeneto** [comment]
> On the janus server you can put a admin key witch you will need to give to the FREE server so it can create and list the video streams.

Two different things: one thing is janus `admin_key`, another one is the `api_secret` (there is also one more "key", also not used by us: `admin_secret`). 

My point is: `api_secret` or  `JANUS_API_SECRET`  in your proposal is not necessary. Only the address and port along with `JANUS_STREAM_ADMIN_KEY`.

**Comment by bgeneto** [comment]
Returning to the main issue here: reverse proxy support....
I propose the following changes to the `settings.py` file: 
```python
    # Support reverse proxy in https
    if env.bool('FREE_REVERSE_PROXY'):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
        USE_X_FORWARDED_HOST = True
        USE_X_FORWARDED_PORT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
```
Along with this new env variable in .env-template file: 

`FREE_REVERSE_PROXY="on"`

Because things didn't work properly without the `COOKIE_SECURE` settings for me (https protocol).
